PANTRY_PATH_DEFAULT = "~/Documents/myPantry.txt"
RECIPE_BOOK_PATH_DEFAULT = "~/Documents/myRecipes.txt"
CATEGORY_DEFAULT = ""
IS_FROZEN_DEFAULT = FALSE
IS_STAPLE_DEFAULT = TRUE
INGREDIENTS_DEFAULT = []
DIRECTIONS_DEFAULT = ""
